services:
  - type: web
    name: cloud-mining-backend
    env: node
    region: singapore
    plan: free
    buildCommand: npm install && npx prisma generate && npm run build
    startCommand: npx prisma db push --accept-data-loss && npx ts-node prisma/seed.ts && npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: DIRECT_URL
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: PLATFORM_TRC20_RECEIVER_ADDRESS
        value: TF73CSgKBtnu5kKJaX6AcGMVphD6Wg61An
      - key: MIN_WITHDRAWAL_AMOUNT
        value: "5.0"
      - key: WITHDRAWAL_FEE
        value: "1.0"

  - type: static
    name: cloud-mining-frontend
    region: singapore
    plan: free
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
